channels:
  - conda-forge
  - bioconda
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - bioconda::stacks
  - bioconda::bwa-mem2
  - bioconda::vcftools
  - bioconda::cutadapt
  - bioconda::samtools
  - pv
